### ISSUE TITLE
java.lang.UnsupportedClassVersionError: edu/berkeley/wtchoi/gv/GraphViz

### ISSUE THREAD

**Issue by kavitadixit** [wtchoi/SwiftHand#4]
Hi,

I amtrying to run this tool however getting this java.lang.UnsupportedClassVersionError: edu/berkeley/wtchoi/gv/GraphViz error.I AM USING JDK 1.6.
please let me know if i need to do any changes.

Thanks,
Kavita

**Comment by wtchoi** [comment]
The front end compilation script is now available.
