### ISSUE TITLE
How to test an arbitrary app using SwiftHand

### ISSUE THREAD

**Issue by hjhjw1991** [wtchoi/SwiftHand#5]
Hi there,

I'm a graduate student researching on testing. I noticed that your tool seems to be able to test and develop a good-enough model for an apk file.
I tried but failed when testing my own apk. It says "main activity is not specified". then i notice that SwiftHand includes a front-end package of source codes.
 I wonder how to get start testing my own apk with the front-end codes.

best wishes.

**Comment by wtchoi** [comment]
Good news. A build script for the front-end is now available.
You can test an arbitrary application using it.
